# Generated by Django 5.2.1 on 2025-05-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uglobals', '0002_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
    ]
